### PR TITLE
activities

### PR DESCRIPTION
**Pull request by JanssensLuc**

### CODE REVIEW

**Review by JanssensLuc — COMMENTED** [review]
Approved

**Review by LucJanssens — APPROVED** [review]

**Review by LucJanssens — APPROVED** [review]

**Review by LucJanssens — APPROVED** [review]
This is GOOOD

**Review by LucJanssens — CHANGES_REQUESTED** [review]
This is looking Splendid

**Review by LucJanssens — APPROVED** [review]

**Review by LucJanssens — APPROVED** [review]
This Good  finish it off

**Pull request merged**
